/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VocabularyRouteImport } from './routes/vocabulary'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVocabularyRouteImport } from './routes/api/vocabulary'
import { Route as ApiTranslateRouteImport } from './routes/api/translate'
import { Route as ApiTextsRouteImport } from './routes/api/texts'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const VocabularyRoute = VocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVocabularyRoute = ApiVocabularyRouteImport.update({
  id: '/api/vocabulary',
  path: '/api/vocabulary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranslateRoute = ApiTranslateRouteImport.update({
  id: '/api/translate',
  path: '/api/translate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTextsRoute = ApiTextsRouteImport.update({
  id: '/api/texts',
  path: '/api/texts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/vocabulary': typeof VocabularyRoute
  '/api/texts': typeof ApiTextsRoute
  '/api/translate': typeof ApiTranslateRoute
  '/api/vocabulary': typeof ApiVocabularyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/vocabulary': typeof VocabularyRoute
  '/api/texts': typeof ApiTextsRoute
  '/api/translate': typeof ApiTranslateRoute
  '/api/vocabulary': typeof ApiVocabularyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/vocabulary': typeof VocabularyRoute
  '/api/texts': typeof ApiTextsRoute
  '/api/translate': typeof ApiTranslateRoute
  '/api/vocabulary': typeof ApiVocabularyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/vocabulary'
    | '/api/texts'
    | '/api/translate'
    | '/api/vocabulary'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/vocabulary'
    | '/api/texts'
    | '/api/translate'
    | '/api/vocabulary'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/vocabulary'
    | '/api/texts'
    | '/api/translate'
    | '/api/vocabulary'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  VocabularyRoute: typeof VocabularyRoute
  ApiTextsRoute: typeof ApiTextsRoute
  ApiTranslateRoute: typeof ApiTranslateRoute
  ApiVocabularyRoute: typeof ApiVocabularyRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vocabulary': {
      id: '/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof VocabularyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vocabulary': {
      id: '/api/vocabulary'
      path: '/api/vocabulary'
      fullPath: '/api/vocabulary'
      preLoaderRoute: typeof ApiVocabularyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/translate': {
      id: '/api/translate'
      path: '/api/translate'
      fullPath: '/api/translate'
      preLoaderRoute: typeof ApiTranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/texts': {
      id: '/api/texts'
      path: '/api/texts'
      fullPath: '/api/texts'
      preLoaderRoute: typeof ApiTextsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  VocabularyRoute: VocabularyRoute,
  ApiTextsRoute: ApiTextsRoute,
  ApiTranslateRoute: ApiTranslateRoute,
  ApiVocabularyRoute: ApiVocabularyRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
